### PR TITLE
pass TSD pw to tacl_auth as env var

### PR DESCRIPTION
**Pull request by f-krull**
Didn't test

https://github.com/unioslo/tsd-s3cmd/commit/ea3c0d42c1c9db37eb5f6cf595ddf75048806fc8#r47686508

### CODE REVIEW

**Comment by leondutoit** [comment]
Cool. I'd be happy to merge once you've tested it.

**Comment by f-krull** [comment]
Sorry, have to pass on that one. I'm not using the s3 API. This is as good as it gets.

**Comment by leondutoit** [comment]
evidently

**Comment by f-krull** [comment]
>  PRs welcome.

**Comment by leondutoit** [comment]
Um ok, anyways, I will try to find time to test this in the near future.

**Comment by f-krull** [comment]
Great. I only changed two lines. Feel free to review and disagree.

**Pull request merged**
